theme: minima
url: https://brady-decouto.github.io
baseurl: /BLAPLab.github.io

header_pages:
  - index.md
  - about.md
  - people.md
  # add these as you create them:
  # - projects.md
  # - publications.md
  # - contact.md
